#!/usr/bin/env bash

set -ueEo pipefail

if ! dnf needs-restarting --reboothint; then
  systemctl reboot --message='Rebooting after dnf-automatic updates'
fi

mapfile -t services < <(dnf needs-restarting --services)
echo "Restarting ${services[*]}"
printf '%s\n' "${services[@]}" | xargs --no-run-if-empty --max-args=1 systemctl restart
